version: '3.7'
services:
  app:
    container_name: app
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules/